# source: https://www.buzzfeed.com/craigsilverman/top-fake-news-of-2016
# list exported from https://docs.google.com/spreadsheets/d/1sTkRkHLvZp9XlJOynYMXGslKY9fuB_e-2mrxqgLwvZY
# (It's possible some could be judged as satirical.)
buzzfeed_96 <- c(
  "abcnews.com.co", 
  "adobochronicles.com", 
  "alynews.com", 
  "associatedmediacoverage.com", 
  "baldwinpost.com", 
  "baltimoregazette.com", 
  "bizstandardnews.com", 
  "burrardstreetjournal.com", 
  "cartelpress.com", 
  "celebtricity.com", 
  "channel16news.com", 
  "channel17news.com", 
  "channel18news.com", 
  "christiantimesnewspaper.com", 
  "civictribune.com", 
  "clancyreport.com", 
  "dailycurrant.com", 
  "dailyfinesser.com", 
  "dailynews11.com", 
  "dailynews3.com", 
  "dailynews33.com", 
  "dailynews5.com", 
  "denverguardian.com", 
  "empireherald.com", 
  "empirenews.net", 
  "empiresports.co", 
  "en.mediamass.net", 
  "freddymag.com", 
  "globalassociatednews.com", 
  "headlinebrief.com", 
  "heaviermetal.net", 
  "hotglobalnews.com", 
  "huzlers.com", 
  "kata33.com", 
  "klponews.com", 
  "km8news.com", 
  "kmt11.com", 
  "knp7.com", 
  "krbcnews.com", 
  "kspm33.com", 
  "kupr7.com", 
  "ky12news.com", 
  "ky6news.com", 
  "kypo6.com", 
  "landrypost.com", 
  "localnews33.com", 
  "lopezreport.com", 
  "maywoodpost.com", 
  "mbynews.com", 
  "mckenziepost.com", 
  "msnbc.website", 
  "nationalreport.net", 
  "ncscooper.com", 
  "news14kgpn.com", 
  "news14now.com", 
  "news4ktla.com", 
  "newsbiscuit.com", 
  "newsbuzzdaily.com", 
  "newsdaily10.com", 
  "newsdaily27.com", 
  "newsexaminer.net", 
  "newshubs.info", 
  "newslo.com", 
  "newsnow17.com", 
  "newswatch33.com", 
  "notallowedto.com", 
  "now8news.com", 
  "nymeta.co", 
  "oreillypost.com", 
  "politicops.com", 
  "react365.com", 
  "realnewsrightnow.com", 
  "rilenews.com", 
  "satiratribune.com", 
  "scrapetv.com", 
  "straightstoned.com", 
  "stuppid.com", 
  "thebostontribune.com", 
  "thenationalsun.com", 
  "thenewsnerd.com", 
  "theracketreport.com", 
  "thereporterz.com", 
  "thevalleyreport.com", 
  "tmzhiphop.com", 
  "unitedmediapublishing.com", 
  "wcpm3.com", 
  "wftj8news.com", 
  "witscience.org", 
  "wleb21.com", 
  "wm21news.com", 
  "wmacnews.com", 
  "wmb36.com", 
  "worldnewsdailyreport.com", 
  "wrejnews.com", 
  "wrpt16.com", 
  "wtoe5news.com"
)

# create-your-own-fake-news-sites
# source: https://www.buzzfeed.com/craigsilverman/create-your-own-fake-news-sites-are-booming-on-facebook-and
CS_5_29_17 <- tolower(c(
  "Channel23news.com",
  "channel22news.com",
  "channel28news.com",
  "Channel34News.com",
  "Channel45News.com",
  # run by same person as above
  "react365.com",
  "famousviralstories.com",
  # run by a different person
  "actualite.co",
  "actualites.co",
  "france.actualites.co",
  "paris.actualites.co",
  "belgique.actualites.co",
  "thebreakingnews.co",
  "noticias365.info",
  "flashinfo.org",
  "12minutos.com",
  "24aktuelles.com"
))

# Known to publish hoaxes
# source: https://www.buzzfeed.com/craigsilverman/this-false-story-about-a-husband-and-wife-discovering?utm_term=.asY8Pn7bQ#.irRAL1DQo
CS_4_17_17 <- tolower(c(
  "MississippiHerald.com",
  "alabamaobserver.com",
  "floridasunpost.com",
  "bostonleader.com",
  "battypost.com",
  # registered to same person
  "pressunion.org",
  "BorderHerald.com",
  "WeekendHerald.com",
  "DenverInquirer.com",
  "TelegraphSun.com"
))

# an-ad-network-that-works-with-fake-news-sites-just-launched an initiative to remove fake news from its network
# (note: at time of article, revcontent had only removed first 3, claiming the rest were satire)
# source: https://www.buzzfeed.com/craigsilverman/an-ad-network-that-works-with-fake-news-sites-just-launched
# note also: all of these are in CS_4_4_17 below
CS_6_5_17 <- tolower(c(
  "Celebtricity.com",
  "TMZComedy.com",
  "notallowedto.com",
  "ViralMugshot.com",
  "NationalReport.net",
  "TheNoCHill.com",
  "FedsAlert.com",
  "NationalReport.net",
  "dailyfinesser.com",
  "huzlers.com",
  "ncscooper.com",
  "newsbiscuit.com",
  "badcriminals.com",
  "drugsofficial.com",
  "freewoodpost.com",
  "qualitysharing.com",
  "stuppid.com",
  "thefrt.com",
  "uspoln.com",
  "viralcocaine.com",
  "viralstuppid.com"
))

# npr-finds-the-head-of-a-covert-fake-news-operation-in-the-suburbs
# source: http://www.npr.org/sections/alltechconsidered/2016/11/23/503146770/npr-finds-the-head-of-a-covert-fake-news-operation-in-the-suburbs, 
# (linked from https://www.buzzfeed.com/craigsilverman/an-ad-network-that-works-with-fake-news-sites-just-launched)
CS_11_23_16 <- tolower(c(
  "USAToday.com.co"
))

# fake-news-real-ads
# source: https://www.buzzfeed.com/craigsilverman/fake-news-real-ads
# Of these 108, 73 are already on earlier blacklist; only 35 are new.
CS_4_4_17 <- tolower(c(
  "newslo.com",
  "politicops.com",
  "adobochronicles.com",
  "bizstandardnews.com",
  "burrardstreetjournal.com",
  "butthatsnoneofmybusiness.com",
  "dailyfinesser.com",
  "empireherald.com",
  "en.mediamass.net",
  "huzlers.com",
  "krbcnews.com",
  "ncscooper.com",
  "newsbiscuit.com",
  "newshubs.info",
  "react365.com",
  "realnewsrightnow.com",
  "thenationalsun.com",
  "thenewsnerd.com",
  "thevalleyreport.com",
  "cartelreport.com",
  "folksvideo.com",
  "dailycurrant.com",
  "empirenews.net",
  "empiresports.co",
  "news4ktla.com",
  "now8news.com",
  "theracketreport.com",
  "undergroundnewsreport.com",
  "persecutes.com",
  "viralmugshot.com",
  "viralspeech.com",
  "kata33.com",
  "landrypost.com",
  "wm21news.com",
  "civictribune.com",
  "straightstoned.com",
  "associatedmediacoverage.com",
  "cnn.com.de",
  "newsexaminer.net",
  "stgeorgegazette.com",
  "unitedmediapublishing.com",
  "tmzbreaking.com",
  "tmzworldnews.com",
  "tmzworldstarnews.com",
  "viralactions.com",
  "badcriminals.com",
  "celebtricity.com",
  "drugsofficial.com",
  "everydaybreakingnews.com",
  "fedsalert.com",
  "freewoodpost.com",
  "nationalreport.net",
  "notallowedto.com",
  "qualitysharing.com",
  "stuppid.com",
  "thefrt.com",
  "thelastlineofdefense.org",
  "thenochill.com",
  "tmzcomedy.com",
  "uspoln.com",
  "viralcocaine.com",
  "viralstuppid.com",
  "20minutenews.com",
  "abcnews.com.co",
  "alertchild.com",
  "alynews.com",
  "areyouasleep.com",
  "baltimoregazette.com",
  "cartelpress.com",
  "channel16news.com",
  "channel17news.com",
  "channel18news.com",
  "channel5000.com",
  "christiantimesnewspaper.com",
  "clancyreport.com",
  "dailynews11.com",
  "denverguardian.com",
  "heaviermetal.net",
  "jokerviral.com",
  "kspm33.com",
  "kupr7.com",
  "ky6news.com",
  "kypo6.com",
  "mbynews.com",
  "mckenziepost.com",
  "mrnewswatch.com",
  "msnbc.website",
  "newsbuzzdaily.com",
  "newsnow17.com",
  "newswatch33.com",
  "oreillypost.com",
  "rilenews.com",
  "satiratribune.com",
  "scrapetv.com",
  "smhwtfnews.com",
  "thebostontribune.com",
  "thereporterz.com",
  "tmzbusiness.com",
  "tmzhiphop.com",
  "tmzuncut.com",
  "tmzurban.com",
  "viraldevil.com",
  "viralpropaganda.com",
  "witscience.org",
  "wleb21.com",
  "worldnewsdailyreport.com",
  "theavocadonews.com",
  "ViralSpeech.com",
  "theseattletribune.com",
  "Persecutes.com"
))

# source: https://www.buzzfeed.com/craigsilverman/the-strangest-fake-news-empire?utm_term=.sfyYk43bA#.pdkGNn6bA
# which points to this google doc: https://docs.google.com/spreadsheets/d/1wFUEGdTVza_NEJttHYYG3vBQXwK055S1wWsixpd_C4o/edit?usp=sharing
CS_12_16_2016 <- c(
  "alynews.com", 
  "clancyreport.com", 
  "headlinebrief.com", 
  "knp7.com", 
  "kspm33.com", 
  "ky6news.com", 
  "lopezreport.com", 
  "mbynews.com", 
  "mckenziepost.com", 
  "newsdaily27.com", 
  "oreillypost.com", 
  "wcpm3.com", 
  "wleb21.com"
)

# source: https://www.buzzfeed.com/craigsilverman/these-are-50-of-the-biggest-fake-news-hits-on-facebook-in
# which pointed to https://github.com/BuzzFeedNews/2017-12-fake-news-top-50/data/sites_2017.csv
# Methodology: they used their own previous lists & database, plus Politifact's April 2017 list. From Politifact, only took sites that, as determined by 2 Buzzfeed reviewers,
# "consistently publish completely false stories." Main text of article is even stronger: "websites that entirely or consistently publish articles with a completely false central claim."
# "We also compared our 2016 site list to PolitiFact’s list of websites, and found seven sites that would have qualified for our 2016 list had we known about them at the time."
#   <-- which implies, I think, that the rest of the 2017 list wasn't around in 2016.
buzzfeed_top2017 = as.character(read.csv("buzzfeed_sites_2017.csv")[,1])



# Combine with existing blacklists
# ---------

buzzfeed <- unique(tolower(c(buzzfeed_96, CS_5_29_17, CS_4_17_17, CS_6_5_17, CS_11_23_16, CS_4_4_17, CS_12_16_2016)))
buzzfeed_new = unique(tolower(c(buzzfeed, buzzfeed_top2017)))
